spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: spring
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
store:
  storeNo: Store235
  storeName: Jack And Jill
  storeManager: James
  openingHrs: 9
  closingHrs: 10
  location: Hawaii
pharmacy:
  active:
    profile:
      test: Hello from dev...
