server:
  port: 8081
spring:
  application:
    name: pharmacy-service
management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - refresh